GET http://localhost:4000/fires
Content-Type: application/json
Authorization: 53271b2701a716aaf12484b715c4cdda

{
    "locCode": 2
}


###

POST http://localhost:4000/fires
Content-Type: application/json
Authorization: 53271b2701a716aaf12484b715c4cdda

{
    "locCode": 3,
    "severity": 2,
    "description": "Medium severity grass fire in the adelaide hills area."
}